// <copyright file="ConsolidateDirectoryForm.Designer.cs" company="PUblicDomain.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />
namespace ConsolidateDirectory
{
    partial class ConsolidateDirectoryForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
        	System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ConsolidateDirectoryForm));
        	this.mainMenuStrip = new System.Windows.Forms.MenuStrip();
        	this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.dailyReleasesPublicDomainDailycomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.originalThreadDonationCodercomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.sourceCodeGithubcomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
        	this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.minimizeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.mainStatusStrip = new System.Windows.Forms.StatusStrip();
        	this.mainToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.countToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.patternTextBox = new System.Windows.Forms.TextBox();
        	this.patternReferenceLinkLabel = new System.Windows.Forms.LinkLabel();
        	this.filterLabel = new System.Windows.Forms.Label();
        	this.tableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
        	this.groupBox1 = new System.Windows.Forms.GroupBox();
        	this.moveFilesRadioButton = new System.Windows.Forms.RadioButton();
        	this.copyFilesRadioButton = new System.Windows.Forms.RadioButton();
        	this.consolidateDirectoryButton = new System.Windows.Forms.Button();
        	this.groupBox2 = new System.Windows.Forms.GroupBox();
        	this.radioButton3 = new System.Windows.Forms.RadioButton();
        	this.radioButton4 = new System.Windows.Forms.RadioButton();
        	this.toolStripProgressBar1 = new System.Windows.Forms.ToolStripProgressBar();
        	this.folderBrowserDialog = new System.Windows.Forms.FolderBrowserDialog();
        	this.mainMenuStrip.SuspendLayout();
        	this.mainStatusStrip.SuspendLayout();
        	this.tableLayoutPanel.SuspendLayout();
        	this.groupBox1.SuspendLayout();
        	this.groupBox2.SuspendLayout();
        	this.SuspendLayout();
        	// 
        	// mainMenuStrip
        	// 
        	this.mainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.fileToolStripMenuItem,
        	        	        	this.helpToolStripMenuItem,
        	        	        	this.minimizeToolStripMenuItem});
        	this.mainMenuStrip.Location = new System.Drawing.Point(0, 0);
        	this.mainMenuStrip.Name = "mainMenuStrip";
        	this.mainMenuStrip.Size = new System.Drawing.Size(244, 24);
        	this.mainMenuStrip.TabIndex = 21;
        	// 
        	// fileToolStripMenuItem
        	// 
        	this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.exitToolStripMenuItem});
        	this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
        	this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
        	this.fileToolStripMenuItem.Text = "&File";
        	// 
        	// exitToolStripMenuItem
        	// 
        	this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
        	this.exitToolStripMenuItem.Size = new System.Drawing.Size(92, 22);
        	this.exitToolStripMenuItem.Text = "E&xit";
        	this.exitToolStripMenuItem.Click += new System.EventHandler(this.OnExitToolStripMenuItemClick);
        	// 
        	// helpToolStripMenuItem
        	// 
        	this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.dailyReleasesPublicDomainDailycomToolStripMenuItem,
        	        	        	this.originalThreadDonationCodercomToolStripMenuItem,
        	        	        	this.sourceCodeGithubcomToolStripMenuItem,
        	        	        	this.toolStripSeparator2,
        	        	        	this.aboutToolStripMenuItem});
        	this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
        	this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
        	this.helpToolStripMenuItem.Text = "&Help";
        	// 
        	// dailyReleasesPublicDomainDailycomToolStripMenuItem
        	// 
        	this.dailyReleasesPublicDomainDailycomToolStripMenuItem.Name = "dailyReleasesPublicDomainDailycomToolStripMenuItem";
        	this.dailyReleasesPublicDomainDailycomToolStripMenuItem.Size = new System.Drawing.Size(289, 22);
        	this.dailyReleasesPublicDomainDailycomToolStripMenuItem.Text = "Daily releases @ PublicDomainDaily.com";
        	// 
        	// originalThreadDonationCodercomToolStripMenuItem
        	// 
        	this.originalThreadDonationCodercomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("originalThreadDonationCodercomToolStripMenuItem.Image")));
        	this.originalThreadDonationCodercomToolStripMenuItem.Name = "originalThreadDonationCodercomToolStripMenuItem";
        	this.originalThreadDonationCodercomToolStripMenuItem.Size = new System.Drawing.Size(289, 22);
        	this.originalThreadDonationCodercomToolStripMenuItem.Text = "&Original thread @ DonationCoder.com";
        	// 
        	// sourceCodeGithubcomToolStripMenuItem
        	// 
        	this.sourceCodeGithubcomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("sourceCodeGithubcomToolStripMenuItem.Image")));
        	this.sourceCodeGithubcomToolStripMenuItem.Name = "sourceCodeGithubcomToolStripMenuItem";
        	this.sourceCodeGithubcomToolStripMenuItem.Size = new System.Drawing.Size(289, 22);
        	this.sourceCodeGithubcomToolStripMenuItem.Text = "Source code @ Github.com";
        	// 
        	// toolStripSeparator2
        	// 
        	this.toolStripSeparator2.Name = "toolStripSeparator2";
        	this.toolStripSeparator2.Size = new System.Drawing.Size(286, 6);
        	// 
        	// aboutToolStripMenuItem
        	// 
        	this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
        	this.aboutToolStripMenuItem.Size = new System.Drawing.Size(289, 22);
        	this.aboutToolStripMenuItem.Text = "&About...";
        	// 
        	// minimizeToolStripMenuItem
        	// 
        	this.minimizeToolStripMenuItem.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
        	this.minimizeToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("minimizeToolStripMenuItem.Image")));
        	this.minimizeToolStripMenuItem.Name = "minimizeToolStripMenuItem";
        	this.minimizeToolStripMenuItem.Size = new System.Drawing.Size(28, 20);
        	this.minimizeToolStripMenuItem.Visible = false;
        	// 
        	// mainStatusStrip
        	// 
        	this.mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.mainToolStripStatusLabel,
        	        	        	this.countToolStripStatusLabel});
        	this.mainStatusStrip.Location = new System.Drawing.Point(0, 183);
        	this.mainStatusStrip.Name = "mainStatusStrip";
        	this.mainStatusStrip.Size = new System.Drawing.Size(244, 22);
        	this.mainStatusStrip.SizingGrip = false;
        	this.mainStatusStrip.TabIndex = 20;
        	this.mainStatusStrip.Text = "HELLO";
        	// 
        	// mainToolStripStatusLabel
        	// 
        	this.mainToolStripStatusLabel.Name = "mainToolStripStatusLabel";
        	this.mainToolStripStatusLabel.Size = new System.Drawing.Size(90, 17);
        	this.mainToolStripStatusLabel.Text = "Files to process:";
        	// 
        	// countToolStripStatusLabel
        	// 
        	this.countToolStripStatusLabel.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.countToolStripStatusLabel.Name = "countToolStripStatusLabel";
        	this.countToolStripStatusLabel.Size = new System.Drawing.Size(75, 17);
        	this.countToolStripStatusLabel.Text = "Calculating...";
        	// 
        	// patternTextBox
        	// 
        	this.tableLayoutPanel.SetColumnSpan(this.patternTextBox, 2);
        	this.patternTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.patternTextBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.patternTextBox.Location = new System.Drawing.Point(3, 23);
        	this.patternTextBox.Name = "patternTextBox";
        	this.patternTextBox.Size = new System.Drawing.Size(238, 20);
        	this.patternTextBox.TabIndex = 0;
        	this.patternTextBox.Text = "*.*";
        	this.patternTextBox.Leave += new System.EventHandler(this.OnPatternTextBoxLeave);
        	// 
        	// patternReferenceLinkLabel
        	// 
        	this.patternReferenceLinkLabel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.patternReferenceLinkLabel.Location = new System.Drawing.Point(125, 0);
        	this.patternReferenceLinkLabel.Name = "patternReferenceLinkLabel";
        	this.patternReferenceLinkLabel.Size = new System.Drawing.Size(116, 20);
        	this.patternReferenceLinkLabel.TabIndex = 1;
        	this.patternReferenceLinkLabel.TabStop = true;
        	this.patternReferenceLinkLabel.Text = "(Pattern &reference)";
        	this.patternReferenceLinkLabel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
        	this.patternReferenceLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.OnPatternReferenceLinkLabelLinkClicked);
        	// 
        	// filterLabel
        	// 
        	this.filterLabel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.filterLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.filterLabel.Location = new System.Drawing.Point(3, 0);
        	this.filterLabel.Name = "filterLabel";
        	this.filterLabel.Size = new System.Drawing.Size(116, 20);
        	this.filterLabel.TabIndex = 0;
        	this.filterLabel.Text = "Filter:";
        	this.filterLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
        	// 
        	// tableLayoutPanel
        	// 
        	this.tableLayoutPanel.ColumnCount = 2;
        	this.tableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
        	this.tableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
        	this.tableLayoutPanel.Controls.Add(this.groupBox1, 0, 2);
        	this.tableLayoutPanel.Controls.Add(this.filterLabel, 0, 0);
        	this.tableLayoutPanel.Controls.Add(this.patternReferenceLinkLabel, 1, 0);
        	this.tableLayoutPanel.Controls.Add(this.patternTextBox, 0, 1);
        	this.tableLayoutPanel.Controls.Add(this.consolidateDirectoryButton, 0, 3);
        	this.tableLayoutPanel.Controls.Add(this.groupBox2, 1, 2);
        	this.tableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.tableLayoutPanel.Location = new System.Drawing.Point(0, 24);
        	this.tableLayoutPanel.Name = "tableLayoutPanel";
        	this.tableLayoutPanel.RowCount = 4;
        	this.tableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
        	this.tableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
        	this.tableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
        	this.tableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
        	this.tableLayoutPanel.Size = new System.Drawing.Size(244, 159);
        	this.tableLayoutPanel.TabIndex = 22;
        	// 
        	// groupBox1
        	// 
        	this.groupBox1.Controls.Add(this.moveFilesRadioButton);
        	this.groupBox1.Controls.Add(this.copyFilesRadioButton);
        	this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.groupBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.groupBox1.Location = new System.Drawing.Point(3, 43);
        	this.groupBox1.Name = "groupBox1";
        	this.groupBox1.Size = new System.Drawing.Size(116, 78);
        	this.groupBox1.TabIndex = 23;
        	this.groupBox1.TabStop = false;
        	this.groupBox1.Text = "Mode";
        	// 
        	// moveFilesRadioButton
        	// 
        	this.moveFilesRadioButton.Checked = true;
        	this.moveFilesRadioButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.moveFilesRadioButton.Location = new System.Drawing.Point(12, 19);
        	this.moveFilesRadioButton.Name = "moveFilesRadioButton";
        	this.moveFilesRadioButton.Size = new System.Drawing.Size(104, 24);
        	this.moveFilesRadioButton.TabIndex = 1;
        	this.moveFilesRadioButton.TabStop = true;
        	this.moveFilesRadioButton.Text = "&Move files";
        	this.moveFilesRadioButton.UseVisualStyleBackColor = true;
        	// 
        	// copyFilesRadioButton
        	// 
        	this.copyFilesRadioButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.copyFilesRadioButton.Location = new System.Drawing.Point(12, 49);
        	this.copyFilesRadioButton.Name = "copyFilesRadioButton";
        	this.copyFilesRadioButton.Size = new System.Drawing.Size(104, 24);
        	this.copyFilesRadioButton.TabIndex = 1;
        	this.copyFilesRadioButton.Text = "&Copy files";
        	this.copyFilesRadioButton.UseVisualStyleBackColor = true;
        	// 
        	// consolidateDirectoryButton
        	// 
        	this.tableLayoutPanel.SetColumnSpan(this.consolidateDirectoryButton, 2);
        	this.consolidateDirectoryButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.consolidateDirectoryButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.consolidateDirectoryButton.Location = new System.Drawing.Point(3, 127);
        	this.consolidateDirectoryButton.Name = "consolidateDirectoryButton";
        	this.consolidateDirectoryButton.Size = new System.Drawing.Size(238, 29);
        	this.consolidateDirectoryButton.TabIndex = 3;
        	this.consolidateDirectoryButton.Text = "Consolidate directory";
        	this.consolidateDirectoryButton.UseVisualStyleBackColor = true;
        	this.consolidateDirectoryButton.Click += new System.EventHandler(this.OnConsolidateDirectoryButtonClick);
        	// 
        	// groupBox2
        	// 
        	this.groupBox2.Controls.Add(this.radioButton3);
        	this.groupBox2.Controls.Add(this.radioButton4);
        	this.groupBox2.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.groupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.groupBox2.Location = new System.Drawing.Point(125, 43);
        	this.groupBox2.Name = "groupBox2";
        	this.groupBox2.Size = new System.Drawing.Size(116, 78);
        	this.groupBox2.TabIndex = 24;
        	this.groupBox2.TabStop = false;
        	this.groupBox2.Text = "Destination";
        	// 
        	// radioButton3
        	// 
        	this.radioButton3.Checked = true;
        	this.radioButton3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.radioButton3.Location = new System.Drawing.Point(12, 19);
        	this.radioButton3.Name = "radioButton3";
        	this.radioButton3.Size = new System.Drawing.Size(104, 24);
        	this.radioButton3.TabIndex = 2;
        	this.radioButton3.TabStop = true;
        	this.radioButton3.Text = "&Selected";
        	this.radioButton3.UseVisualStyleBackColor = true;
        	// 
        	// radioButton4
        	// 
        	this.radioButton4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.radioButton4.Location = new System.Drawing.Point(12, 49);
        	this.radioButton4.Name = "radioButton4";
        	this.radioButton4.Size = new System.Drawing.Size(104, 19);
        	this.radioButton4.TabIndex = 2;
        	this.radioButton4.Text = "&Browse";
        	this.radioButton4.UseVisualStyleBackColor = true;
        	// 
        	// toolStripProgressBar1
        	// 
        	this.toolStripProgressBar1.Name = "toolStripProgressBar1";
        	this.toolStripProgressBar1.Size = new System.Drawing.Size(100, 15);
        	// 
        	// folderBrowserDialog
        	// 
        	this.folderBrowserDialog.Description = "Destination for consolidated files";
        	// 
        	// ConsolidateDirectoryForm
        	// 
        	this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
        	this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        	this.ClientSize = new System.Drawing.Size(244, 205);
        	this.Controls.Add(this.tableLayoutPanel);
        	this.Controls.Add(this.mainMenuStrip);
        	this.Controls.Add(this.mainStatusStrip);
        	this.Name = "ConsolidateDirectoryForm";
        	this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        	this.Text = "Consolidate Directory";
        	this.mainMenuStrip.ResumeLayout(false);
        	this.mainMenuStrip.PerformLayout();
        	this.mainStatusStrip.ResumeLayout(false);
        	this.mainStatusStrip.PerformLayout();
        	this.tableLayoutPanel.ResumeLayout(false);
        	this.tableLayoutPanel.PerformLayout();
        	this.groupBox1.ResumeLayout(false);
        	this.groupBox2.ResumeLayout(false);
        	this.ResumeLayout(false);
        	this.PerformLayout();
        }
        private System.Windows.Forms.FolderBrowserDialog folderBrowserDialog;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.RadioButton radioButton4;
        private System.Windows.Forms.RadioButton radioButton3;
        private System.Windows.Forms.RadioButton copyFilesRadioButton;
        private System.Windows.Forms.RadioButton moveFilesRadioButton;
        private System.Windows.Forms.ToolStripProgressBar toolStripProgressBar1;
        private System.Windows.Forms.Button consolidateDirectoryButton;
        private System.Windows.Forms.TextBox patternTextBox;
        private System.Windows.Forms.LinkLabel patternReferenceLinkLabel;
        private System.Windows.Forms.Label filterLabel;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel;
        private System.Windows.Forms.ToolStripStatusLabel countToolStripStatusLabel;
        private System.Windows.Forms.ToolStripStatusLabel mainToolStripStatusLabel;
        private System.Windows.Forms.StatusStrip mainStatusStrip;
        private System.Windows.Forms.ToolStripMenuItem minimizeToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem sourceCodeGithubcomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem originalThreadDonationCodercomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem dailyReleasesPublicDomainDailycomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.MenuStrip mainMenuStrip;
    }
}
